### PR TITLE
upgrade contributing input based on designs

### LINKED ISSUE #112: User gets confirmation that their contribution has been saved. (Waiting on Design)
Through the user feedback, people really seem to want some confirmation that they are done...

Is there a super easy way to make this more clear, without fogging the processes without potentially annoying "You're done!" modals. Needs at least one design/ test loop.

@jonlemmon @ahdinosaur

### PR DESCRIPTION
**Pull request by ahdinosaur**
closes #112, closes https://github.com/open-app/cobudget/issues/43.

@jonlemmon, your feedback would be sweet. this is also up on http://staging.cobudget.co.

### CODE REVIEW

**Comment by ahdinosaur** [comment]
@jonlemmon what should the inputs look like when the round is pending or closed? here's what a recent closed round looks like now, but i'd like to get your feedback on what it *should* look like:

**Comment by jonlemmon** [comment]
Hey Mikey, I know it's not ideal, but can we make it look like the following screenshot for now, and we can continue thinking about a better solution for the future? Thanks!

screenshot 2015-02-02 16 36 52

**Comment by ahdinosaur** [comment]
sweet, thanks @jonlemmon. (*^ω^)

**Comment by jonlemmon** [comment]
You're killing it Mikey.

**Pull request merged**
