### PR TITLE
clean and improve styles

### PR DESCRIPTION
**Pull request by ahdinosaur**
i slashed a lot of the existing style code to make it more [based on bootstrap](https://github.com/open-app/cobudget-ui/issues/149), more based on sass variables, and using less custom styling, in the hopes of making it cleaner and easier to maintain. i also want to start taking more ownership of our styling instead of deferring to @derekrazo. some interface elements changed along the way, based on what i saw in @jonlemmon's designs and some personal ad-hoc decisions that i'd love feedback on.

this pull request is best described through screenshots, so here we go. :camera:

@jonlemmon feedback would be amazing, even if it's seemingly pedantic. let me know if there's anything that you want me to change before merging this in, or if you have reservations in general to anything here. i'm keen to hear about your vision of the Cobudget user interface in relation to where it is now, so we can converge the two as we move forward. 

## existing

^ there's no scrollbar, so for example i can't see all the fixed costs in the E S round.

### CODE REVIEW

**Comment by ahdinosaur** [comment]
currently up-to-date version of this and all ready-to-be-merged PRs (cleanup-styles (#150), group-members, contribution-focus (#152), and bucket-contributions (#151)) up on http://staging.cobudget.co.

**Comment by derekrazo** [comment]
Looks sweet! Here's a list of some stuff it would be good to get checked off before the big merge.

* Bucket list items should get the selected hover over instead of underline (needs a color)
* Tabs hover, needs design review
* "Your Funds" doesn't go green when allocations are done
* Remove equation at the bottom left of buckets (implement latest design)

Trust that the structural stuff is great, and I'd like to get @jonlemmon to do a pass at this and comment on some stuff. I notice that bucket details aren't quite at pairty with the designs, but I'm having trouble finding original mockups.

**Comment by ahdinosaur** [comment]
fixed '"Your Funds" and progress bar doesn't go green when allocations are done' as that's a serious bug.

@derekrazo in pursuit of iterative improvement, how do you feel if we were to merge this in as is and move the rest of your tasks into separate issues for future development?

**Comment by ahdinosaur** [comment]
notes from @jonlemmon:

- tabs should be `float: left` and margins corresponding to gutter width.
- page containers should be full width (`container-fluid` in bootstrap).

**Pull request merged**
